### ISSUE TITLE
audio problem

### ISSUE THREAD

**Issue by ilsanto17** [ShanguUncle/UnityChatSDK#9]
Hi, can you tell me what features an Android phone must have to support video calling? because in my tests I have a bad sound: the audio feels bad and you don't hear all the words. I use a samsung galaxy s7.

Best reguards

**Comment by ShanguUncle** [comment]
No special requirements for equipment,you can try open echo.

**Comment by ShanguUncle** [comment]
Please update to the latest version.
https://github.com/ShanguUncle/UnityChatSDK




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ilsanto17"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 凌晨3:36
收件人:&nbsp;"ShanguUncle/UnityChatSDK"<UnityChatSDK@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ShanguUncle/UnityChatSDK] audio problem (#9)




Hi, can you tell me what features an Android phone must have to support video calling? because in my tests I have a bad sound: the audio feels bad and you don't hear all the words. I use a samsung galaxy s7.
 
Best reguards
